### PR TITLE
CookieTokenStorage - change send to sendHeaders

### PR DESCRIPTION
**Pull request by rezaf-dev**
Hello,
Thank you for this package. I have a problem with redirecting after login. Redirect doesn't work because you are using the send for setting the cookie. It shows this error:
`Warning: Cannot modify header information - headers already sent`
 I've replaced send with sendHeader to fix redirects. Please accept this pull request.
Thank you.

### CODE REVIEW

**Comment by vatri** [comment]
Thanks for contribution.

Why it worked before?

**Comment by rezaf-dev** [comment]
Actually, I don't know. It's weird, maybe configs like output_buffering were on before 🤔

**Comment by vatri** [comment]
Hm. No idea.

Also if you have time, you can check if you have some errors in app and if that errors is printed before it sends response.

**Comment by rezaf-dev** [comment]
There aren't any errors. I've tested the "setToken" method isolated, and I couldn't send any response after calling that. Symfony closes the response [here](https://github.com/symfony/symfony/blob/ec00687dabc06e18ed89719e5f15915271a4c962/src/Symfony/Component/HttpFoundation/Response.php#L384) and it's not possible to send anything after this.
I'm curious to find out how it was working before 🤔

**Pull request merged**
